version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: safetodo_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - api_network

  redis:
    image: redis:7-alpine
    container_name: safetodo_redis
    ports:
      - "6379:6379"
    networks:
      - api_network

  web:
    build: .
    container_name: safetodo_web
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      DB_ENGINE: ${DB_ENGINE}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - api_network

volumes:
  postgres_data:

networks:
  api_network:
    driver: bridge
