# Generated by Django 4.2.8 on 2026-01-21 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em Progresso'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Status')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('priority', models.IntegerField(default=0, verbose_name='Prioridade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ('-priority', 'due_date'),
            },
        ),
    ]
