# Generated by Django 4.2.8 on 2026-01-24 00:10

from django.db import migrations


def seed_priority_levels(apps, schema_editor):
    PriorityLevel = apps.get_model('tasks', 'PriorityLevel')

    levels = [
        (1, 'Urgente', 'Mais importante'),
        (2, 'Alta', 'Alta prioridade'),
        (3, 'Media', 'Prioridade media'),
        (4, 'Baixa', 'Prioridade baixa'),
        (5, 'Minima', 'Menos importante'),
    ]

    for level, name, description in levels:
        PriorityLevel.objects.update_or_create(
            level=level,
            defaults={
                'name': name,
                'description': description,
                'is_active': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_priority_level_and_task_priority_level'),
    ]

    operations = [
        migrations.RunPython(seed_priority_levels, migrations.RunPython.noop),
    ]
