# Generated by Django 4.2.8 on 2026-01-24 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_seed_priority_levels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={
                'ordering': ('-priority_level__level', 'due_date'),
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
            },
        ),
    ]
