# Generated by Django 4.2.8 on 2026-01-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_pending_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('created', 'Criada'), ('in_progress', 'Em Progresso'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='created', max_length=20, verbose_name='Status'),
        ),
    ]
